# Generated by Django 5.2 on 2025-04-20 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_branch_semester_subject_note_delete_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="note",
            name="semester",
        ),
        migrations.RemoveField(
            model_name="note",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="note",
            name="user",
        ),
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("course_code", models.CharField(max_length=20)),
                ("course_name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="notes/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notes",
                "verbose_name_plural": "Notes",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.DeleteModel(
            name="Branch",
        ),
        migrations.DeleteModel(
            name="Semester",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.DeleteModel(
            name="Note",
        ),
    ]
