# Generated by Django 5.2 on 2025-04-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_remove_note_branch_remove_note_semester_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                max_length=10,
            ),
        ),
    ]
