# Generated by Django 5.2 on 2025-04-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_alter_notes_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="downloads",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
