# Generated by Django 5.2 on 2025-04-21 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0007_company_placementexperience_placementcomment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name="noterequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="noterequest",
            old_name="date_created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="noterequest",
            old_name="date_updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="noterequest",
            old_name="requested_by",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="noterequest",
            name="deadline",
        ),
        migrations.RemoveField(
            model_name="noterequest",
            name="semester",
        ),
        migrations.RemoveField(
            model_name="noterequest",
            name="subject",
        ),
        migrations.AlterField(
            model_name="noterequest",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("solved", "Solved")],
                default="open",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="noterequest",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="noterequest",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="note_requests",
                to="notes.course",
            ),
        ),
        migrations.CreateModel(
            name="NoteRequestReply",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="notes.noterequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_request_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Note Request Replies",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoteFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="notes_files/")),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="notes.noterequestreply",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="RequestResponse",
        ),
    ]
