# Generated by Django 5.2 on 2025-04-22 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0008_course_alter_noterequest_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noterequest",
            name="course",
        ),
        migrations.RemoveField(
            model_name="noterequestreply",
            name="request",
        ),
        migrations.RemoveField(
            model_name="noterequestreply",
            name="user",
        ),
        migrations.AddField(
            model_name="notefile",
            name="file_extension",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="notefile",
            name="file_size_kb",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="noterequest",
            name="course_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="noterequest",
            name="course_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="noterequest",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("solved", "Solved")],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="noterequest",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="RequestReply",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="notes.noterequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Request replies",
                "ordering": ["created_at"],
            },
        ),
        migrations.AlterField(
            model_name="notefile",
            name="reply",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="notes.requestreply",
            ),
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="NoteRequestReply",
        ),
    ]
